sudo: true

language:
  - cpp

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

before_install:
  - sudo add-apt-repository ppa:ondrej/php -y
  - sudo apt-get update -q
  - sudo apt-get install -q libsodium-dev

script:
  - mkdir build
  - cd build
  - cmake ../
  - make
  - ./tests/runUnitTests

notifications:
  email: false
