sudo: true

language:
  - cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

install:
  - sudo apt-get install -y libsodium-dev

script:
  - mkdir build
  - cd build
  - cmake ../
  - make
  - ctest

notifications:
email: false
