sudo: true

language:
  - cpp

compiler:
  - gcc

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

before_install:
  - sudo apt-get update -q
  - sudo apt-get install -y libsodium-dev

script:
  - mkdir build
  - cd build
  - cmake ../
  - make
  - ctest

notifications:
email: false
