sudo: false

language:
  - cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: "ppa:ondrej/php" # for libsodium-dev
    packages:
      - gcc-7
      - g++-7
      - libsodium-dev

script:
  - export CC=gcc-7
  - export CXX=g++-7
  - mkdir build
  - cd build
  - cmake ../
  - make -j2
  - cd tests/
  - ./runUnitTests

notifications:
  email: false
